repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com/

releases:
  - name: metallb
    namespace: metallb-system
    chart: stable/metallb
    version: 0.12.0
    values:
      - values.yaml
